"""Seam protocols between Claude-lane code (WS-0/3/4/6) and Codex-lane code (WS-1/2/5).

OWNERSHIP: authored by Claude Code (WS-0), part of the frozen contract surface.
READ-ONLY for Codex — implement concrete classes/functions that satisfy these
Protocols in your own modules (carrystar/parsers/, carrystar/store.py,
carrystar/replay.py). Do not edit this file; if a signature is wrong, raise it
as a contract bump, don't fork it.

The agent loop (WS-4) and the API (WS-0) depend ONLY on these Protocols, never
on the concrete Codex modules. Concrete implementations are injected at runtime
via carrystar/seams/registry.py. This is what lets the Claude lane build and
the Codex lane build in parallel without touching each other's files.
"""

from __future__ import annotations

from pathlib import Path
from typing import Protocol, runtime_checkable

from carrystar.contracts import Beat, Mutation, ParsedDoc, TrackerRow


# ---------------------------------------------------------------------------
# WS-1 — Parsers
# ---------------------------------------------------------------------------


@runtime_checkable
class Parser(Protocol):
    """A document parser. One implementation per doc type. Must degrade
    gracefully (return low confidence, never raise) on malformed input —
    the pipeline must not block on a bad parse."""

    def can_parse(self, path: Path) -> bool:
        """Cheap check (usually by extension/sniff) of whether this parser
        handles the file at `path`."""
        ...

    def parse(self, path: Path) -> ParsedDoc:
        """Parse the document into a normalized ParsedDoc whose rows use
        TRACKER_COLUMNS field names and carry per-field provenance under the
        reserved row key "_sources" (list[SourceRef-shaped dicts])."""
        ...


@runtime_checkable
class ParserRegistry(Protocol):
    """Routes a file to the right Parser. WS-1 provides the concrete registry;
    WS-4 calls `parse_path` and never imports individual parsers."""

    def parse_path(self, path: Path) -> ParsedDoc:
        ...


# ---------------------------------------------------------------------------
# WS-2 — Store + xlsx mirror
# ---------------------------------------------------------------------------


@runtime_checkable
class Store(Protocol):
    """Persistence for tracker state + a regenerable xlsx mirror.

    SQLite single-file in the demo (Postgres is a pilot swap, same schema).
    Only approved Mutations are ever applied — there is no auto-commit path
    anywhere in the system.
    """

    def get_state(self) -> list[TrackerRow]:
        """Current tracker rows, in display order."""
        ...

    def get_row(self, row_id: str) -> TrackerRow | None:
        ...

    def apply_mutation(self, mutation: Mutation) -> TrackerRow:
        """Apply an APPROVED (or EDITED) mutation. add_row inserts
        `mutation.proposed_row`; update_field sets `field` on `row_id`.
        Returns the resulting row. Must reject non-approved mutations."""
        ...

    def write_mirror_xlsx(self, path: Path) -> Path:
        """Regenerate the 14-column .xlsx mirror with status_color cell fills,
        preserving the customer's layout. Returns the written path."""
        ...

    def reset(self) -> None:
        """Reload initial tracker state from fixtures (for replays/rehearsals)."""
        ...


# ---------------------------------------------------------------------------
# WS-5 — Replay harness
# ---------------------------------------------------------------------------


@runtime_checkable
class EmailPacket(Protocol):
    """One inbound email + its attachments, as staged under data/emails/<id>/."""

    @property
    def packet_id(self) -> str: ...

    @property
    def account(self) -> str: ...

    @property
    def subject(self) -> str: ...

    @property
    def attachment_paths(self) -> list[Path]: ...


@runtime_checkable
class ReplaySource(Protocol):
    """Feeds packets into the loop. Two modes:
      - live:   run the real pipeline now over staged packets.
      - replay: stream cached agent outputs on a timer (Ross lands last).
    WS-5 owns ordering so the Ross catch is the climax."""

    def packets(self) -> list[EmailPacket]:
        ...

    def beats(self) -> list[Beat]:
        """Ordered inbound emails for the whole replay (across shipments). A
        shipment may contribute multiple beats (order then revision). The loop
        processes these one at a time; WS-5 orders them so Ross lands as the
        climax and its revision follows its order."""
        ...

    def cached_run(self) -> dict | None:
        """Return the serialized prior run (cache/run.json) if present, else None."""
        ...
