"""Generate a SYNTHETIC Ross-shaped packet for Gmail transit (item 5).

These are regenerated by us — NOT the real Mark Edwards customer documents — with
the real shipper letterhead / address / carrier / legal boilerplate stripped, but
the demo's CANONICAL line items kept so the catch and the ground-truth readout
still compute. The real files stay in data/emails/ross-cs02411883/ for the local
Replay path and never transit Google.

Run: uv run python scripts/make_synthetic_packet.py
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

import openpyxl
from docx import Document

OUT = Path(__file__).resolve().parents[1] / "data" / "synthetic"
BOL = "CS02411883"

# canonical lines: (po, eta, etd, container, import_po, style, color, ordered_qty, cartons)
LINES = [
    ("11667250", datetime(2026, 6, 7), datetime(2026, 5, 27), "MATU2103718", "221777", "82355J-IU", "HEATHER GREY", 3605, 103),
    ("11626058", datetime(2026, 5, 20), datetime(2026, 5, 7), "CAAU4749341", "221415", "76284J-AK", "BLACK FLORAL", 9900, 330),
    ("11573709", datetime(2026, 4, 1), datetime(2026, 3, 12), "CAAU9809171", "219094SS", "85739J-AD", "YELLOW", 600, 10),
    ("11573712", datetime(2026, 4, 1), datetime(2026, 3, 12), "CAAU9809171", "219094SS", "85739J-AG", "NAVY", 600, 10),
    ("11722464", datetime(2026, 6, 3), datetime(2026, 5, 21), "XYLU8223291", "221915", "85404J-AA", "BLUE", 10002, 209),
]
# BOL customer-order rows: (po, pkgs, weight, additional)
ORIG_BOL = [("11722464", 209, 9784, "FLOOR LOAD"), ("11573709", 10, 378, ""), ("11573712", 10, 378, ""),
            ("11626058", 330, 6930, ""), ("11667250", 103, 3964, "")]
REV_BOL = [("11722464", 209, 9784, "FLOOR LOAD"), ("11573709", 10, 378, ""), ("11573712", 10, 378, ""),
           ("11626058", 330, 6930, "")]

HEADERS = ["Customer", "Customer PO", "ETA", "ETD", "Container Number",
           "Import Purchase Order Number", "CS BOL", "RTS", "Style On Item", "Color", "Ordered Qty", "CARTONS"]


def make_xlsx() -> Path:
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Sheet1"
    ws.append(HEADERS)
    for po, eta, etd, cont, imp, style, color, oq, ctn in LINES:
        ws.append(["Ross Stores, Inc.", po, eta, etd, f"C#: {cont}", imp, "", "", style, color, oq, ctn])
    p = OUT / "order_export.xlsx"
    wb.save(p)
    return p


def make_bol(rows, name) -> Path:
    doc = Document()
    # generic header block (no real shipper identity)
    t1 = doc.add_table(rows=0, cols=2)
    for a, b in [
        ("Date: JUNE 17, 2026", "MASTER BILL OF LADING"),
        ("Name: DEMO SHIPPER INC. c/o DEMO WAREHOUSE", f"MASTER Bill of Lading Number:  {BOL}"),
        ("Name: ROSS STORES", "CARRIER NAME:    DEMO CARRIER"),
        ("Address: 100 Demo Street", ""),
    ]:
        c = t1.add_row().cells
        c[0].text, c[1].text = a, b
    # customer order number table
    t2 = doc.add_table(rows=0, cols=5)
    hdr = t2.add_row().cells
    for i, h in enumerate(["CUSTOMER ORDER NUMBER", "# PKGS", "WEIGHT", "PALLET/SLIP (CIRCLE ONE)", "ADDITIONAL SHIPPER INFO"]):
        hdr[i].text = h
    tp = tw = 0
    for po, pkgs, weight, addl in rows:
        c = t2.add_row().cells
        c[0].text, c[1].text, c[2].text, c[3].text, c[4].text = po, str(pkgs), str(weight), "", addl
        tp += pkgs
        tw += weight
    c = t2.add_row().cells
    c[0].text, c[1].text, c[2].text = "TOTAL", str(tp), str(tw)
    p = OUT / name
    doc.save(p)
    return p


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    xlsx = make_xlsx()
    orig = make_bol(ORIG_BOL, "BOL_original.docx")
    rev = make_bol(REV_BOL, "BOL_revised.docx")
    print("generated:", xlsx.name, orig.name, rev.name)

    # --- verify they parse to the canonical values ---
    from carrystar.parsers import parse_bol_docx, parse_order_export_xlsx
    oe = parse_order_export_xlsx(xlsx)
    bo = parse_bol_docx(orig)
    br = parse_bol_docx(rev)
    print(f"order export : {len(oe.rows)} rows / {sum(r['ctn_qty'] for r in oe.rows)} ctn  (conf {oe.confidence})")
    print(f"orig BOL     : {len(bo.rows)} rows / {sum(r['ctn_qty'] for r in bo.rows)} ctn  shipment={bo.shipment_id}")
    print(f"revised BOL  : {len(br.rows)} rows / {sum(r['ctn_qty'] for r in br.rows)} ctn")
    hero = next(r for r in oe.rows if r["customer_po"] == "11667250")
    print(f"11667250     : {hero['ctn_qty']} ctn / {hero['style']} / {hero['container']} / etd {hero['date_of_etd']}")
    assert sum(r["ctn_qty"] for r in oe.rows) == 662 and len(oe.rows) == 5
    assert sum(r["ctn_qty"] for r in bo.rows) == 662 and len(bo.rows) == 5
    assert sum(r["ctn_qty"] for r in br.rows) == 559 and len(br.rows) == 4
    assert hero["style"] == "82355J-IU" and hero["container"] == "MATU2103718" and hero["ctn_qty"] == 103
    print("✅ synthetic packet parses to the canonical values")


if __name__ == "__main__":
    main()
